name: Periodic health checks

on:
  # run on push while testing
  push:
    branches:
      - main
  schedule:
    - cron: "30 * 1,2,3 7 *"

jobs:
  health_endpoint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pokedex-94055262.fly.dev/health|http://pokedex-94055262.fly.dev/health
          follow-redirect: true
