name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  tag_release_and_deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Create a new tag except if skipped by a commit message
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        if: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Prepare deployment
        uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
      - name: Deploy
        if: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Ping about a new deployment
        # using the commit for v1.0.4, the latest version at time of writing
        # (though apparently there's been unreleased-but-tagged version since,
        # dunno what that's about)
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          text: Build succeeded!
          description: 'Deployed at https://pokedex-94055262.fly.dev/'
  notify_discord_error:
    if: ${{ github.event_name == 'push' && failure() }}
    needs: [simple_deployment_pipeline, tag_release_and_deploy]
    runs-on: ubuntu-20.04
    steps:
      - name: Ping about failure
        # using the commit for v1.0.4, the latest version at time of writing
        # (though apparently there's been unreleased-but-tagged version since,
        # dunno what that's about)
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          text: Build failed! See below for details.
